Add ability to compute density of states (Lanczos), simpson integrator and new spslicer
eigs/EVSL pull request #5
Opened 2017-04-26 16:22 UTC by AerysL

This pull adds the ability to compute density of states of a matrix by the Lanczos algorithm (landos.c), a function to compute the integrals using simpson's rule and the trapezoidal rule, and a new interval partitioner.

The following files are edited or added:

- evsl.h: Include the new functions (LanDos, spslicer2, simpson, randn_double(generates a normally distributed vector)), in addition to minor spacing automatically done by my editor.
- landos.c: contains the code for the LanDos function
- makefile: add support for new functions and files
- spslice2.h: contains the code for the spslicer2 function
- vect.c: add randn_vector via Box-Muller transformation
- simpson.c: contains the code for simpson function
- LanDos.c: tests the landos, spslicer2 and simpson functions
- testMat.dat: used within the test

2017-04-26 16:37 UTC, liruipeng approved these changes
look good to me.

2017-04-26 16:44 UTC, liruipeng commented on EVSL_1.0/SRC/landos.c
> +  memset(y, 0, npts * sizeof(y[0]));  // y = zeros(size(xdos));
Calloc(y,...). So no need for memset(y,0,...)

2017-04-26 16:52 UTC, AerysL commented on EVSL_1.0/SRC/landos.c
> +  memset(y, 0, npts * sizeof(y[0]));  // y = zeros(size(xdos));
Fixed, thanks

2017-04-26 16:59 UTC, AerysL commented on EVSL_1.0/SRC/landos.c
> +      matvec_genev(A, &V[j * n], &V[(j + 1) * n]);
matvec_genev was removed in the EVS_Bsol, which I have not yet taken into account. I will have to update my code to accommodate this change.

2017-04-26 17:05 UTC, liruipeng requested changes
I take my approval back... it seems that LanDOS only works for standard eig val problem, or B is factored, so you work on L^{-1}*A*L^{-T}. This might be why you call matvec_genev. Have you considered generalized eig problem without Cholesky factorization (with only B-sol)? It will need to change normal inner product to B-inner product. But anyway, the current code is in good shape and should be easy to accommodate B-Sol.

--------------
I might be wrong in my above comment. If these are only for standard eig problem, they are fine. You just to need to change  matvec_genev to matvec_A, which computes y=A*x. Yousef has matlab code for generalized problem as well. So, I thought this one is for everything.

2017-04-27 15:55 UTC, AerysL commented
The Matlab script provided to me only supported the standard eig problem. As such I've just updated the code to support the evsldata format, and improved the tests; thanks for pointing out the changes required. I believe my next task will likely be to generalize it, so your comments will help me complete that.

2017-05-01 16:02 UTC, merged